<?php

use App\Amount;
use App\User;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-05-05 at 18:37:01.
 */
class AmountTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Amount
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Amount(new User);
    }

    /**
     * @test
     */
    public function testGetNumber()
    {
        var_dump($this->object->getAmountWorkingHours(7,1));
    }
}
