<?php

use App\DiscountCalculator;
use App\UnderWear;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2020-05-06 at 17:15:41.
 */
class DiscountCalculatorTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var DiscountCalculator
     */
    protected $object;

    protected function setUp()
    {
        $this->object = new DiscountCalculator;
    }

    public function testCalculate()
    {
        var_dump($this->object->calculate(new UnderWear(),100,3));
    }
}
